// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using cms.Entities;

namespace cms.Migrations
{
    [DbContext(typeof(MasterDBContext))]
    [Migration("20190916164448_ClusterAdded-unq")]
    partial class ClusterAddedunq
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", "'uuid-ossp', '', ''")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("cms.Entities.McsClusters", b =>
                {
                    b.Property<Guid>("ClusterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cluster_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("ActivatedDate")
                        .HasColumnName("activated_date")
                        .HasColumnType("date");

                    b.Property<string>("ClusterCode")
                        .HasColumnName("cluster_code")
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClusterName")
                        .HasColumnName("cluster_name")
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnName("company_id");

                    b.Property<Guid?>("ContactId")
                        .HasColumnName("contact_id");

                    b.Property<DateTime?>("DeactivatedDate")
                        .HasColumnName("deactivated_date")
                        .HasColumnType("date");

                    b.Property<bool>("Status")
                        .HasColumnName("status");

                    b.HasKey("ClusterId");

                    b.HasIndex("ContactId")
                        .IsUnique()
                        .HasName("fki_fk_cluster_contact");

                    b.ToTable("mcs_clusters");
                });

            modelBuilder.Entity("cms.Entities.McsCompanies", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("company_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("ActivatedDate")
                        .HasColumnName("activated_date")
                        .HasColumnType("date");

                    b.Property<string>("CompanyCode")
                        .HasColumnName("company_code")
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnName("company_name")
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ContactId")
                        .HasColumnName("contact_id");

                    b.Property<DateTime>("DeactivatedDate")
                        .HasColumnName("deactivated_date")
                        .HasColumnType("date");

                    b.Property<bool?>("Status")
                        .HasColumnName("status");

                    b.HasKey("CompanyId");

                    b.HasIndex("ContactId")
                        .IsUnique()
                        .HasName("fki_fk_company_contact");

                    b.ToTable("mcs_companies");
                });

            modelBuilder.Entity("cms.Entities.McsContactDetails", b =>
                {
                    b.Property<Guid>("ContactUid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("contact_uid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AddressLine1")
                        .HasColumnName("address_line1")
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AddressLine2")
                        .HasColumnName("address_line2")
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Country")
                        .HasColumnName("country")
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DoorNo")
                        .HasColumnName("door_no")
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LandLineNo")
                        .HasColumnName("land_line_no")
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LandMark")
                        .HasColumnName("land_mark")
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Latitude")
                        .HasColumnName("latitude")
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Longitude")
                        .HasColumnName("longitude")
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MobileNo1")
                        .HasColumnName("mobile_no1")
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MobileNo2")
                        .HasColumnName("mobile_no2")
                        .HasColumnType("character varying(20)");

                    b.Property<string>("State")
                        .HasColumnName("state")
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Zipcode")
                        .HasColumnName("zipcode")
                        .HasColumnType("character varying(200)");

                    b.HasKey("ContactUid");

                    b.ToTable("mcs_contact_details");
                });

            modelBuilder.Entity("cms.Entities.McsRoles", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("ActivatedDate")
                        .HasColumnName("activated_date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeactivatedDate")
                        .HasColumnName("deactivated_date")
                        .HasColumnType("date");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("is_active");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnName("role_name")
                        .HasColumnType("character varying");

                    b.HasKey("RoleId");

                    b.ToTable("mcs_roles");
                });

            modelBuilder.Entity("cms.Entities.MsUsers", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("ActivatedDate")
                        .HasColumnName("activated_date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeactivatedDate")
                        .HasColumnName("deactivated_date")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("first_name")
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnName("gender")
                        .HasColumnType("character varying(20)");

                    b.Property<bool?>("IsActive")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("last_name")
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnName("role_id");

                    b.HasKey("UserId");

                    b.ToTable("ms_users");
                });

            modelBuilder.Entity("cms.Entities.McsClusters", b =>
                {
                    b.HasOne("cms.Entities.McsContactDetails", "Contact")
                        .WithOne("McsClusters")
                        .HasForeignKey("cms.Entities.McsClusters", "ContactId")
                        .HasConstraintName("fk_cluster_contact");
                });

            modelBuilder.Entity("cms.Entities.McsCompanies", b =>
                {
                    b.HasOne("cms.Entities.McsContactDetails", "Contact")
                        .WithOne("McsCompanies")
                        .HasForeignKey("cms.Entities.McsCompanies", "ContactId")
                        .HasConstraintName("fk_company_to_contact");
                });
#pragma warning restore 612, 618
        }
    }
}
